# Generated by Django 4.2.2 on 2023-06-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PR", "Происшествия"),
                    ("POL", "Политика"),
                    ("SP", "Спорт"),
                    ("KU", "Культура"),
                ],
                default="SP",
                max_length=3,
                verbose_name="Категория",
            ),
        ),
    ]
